name: Run Tests and Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Delete package-lock.json
        run: rm package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.COVERALLS_GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

      - name: Build
        run: npm run build

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
